############################# Server Basics #############################

# Role of this node (combined broker+controller)
process.roles=broker,controller

# Unique ID for this node
node.id=1

# Controller quorum bootstrap server
controller.quorum.bootstrap.servers=localhost:9093

# Controller quorum voters (required for KRaft)
controller.quorum.voters=1@localhost:9093

# Cluster ID (use the same when formatting storage)
cluster.id=6mDOxGNBTE-EprEg5gfL1Q

############################# Socket Server Settings #############################

# Listeners: broker for clients, controller for internal KRaft communication
listeners=PLAINTEXT://:9092,CONTROLLER://:9093

# Which listener brokers use to talk to each other
inter.broker.listener.name=PLAINTEXT

# Advertised listeners for clients (only broker listeners!)
advertised.listeners=PLAINTEXT://localhost:9092

# Controller listener names (required for KRaft)
controller.listener.names=CONTROLLER

# Map listener names to security protocols
listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

# Network threads & IO threads
num.network.threads=3
num.io.threads=8

# Socket buffers & max request size
socket.send.buffer.bytes=102400
socket.receive.buffer.bytes=102400
socket.request.max.bytes=104857600

############################# Log Basics #############################

# Where to store Kafka logs
log.dirs=D:\SkyNetix\Java\kafka_2.13-4.1.0\logs

# Default number of partitions per topic
num.partitions=1

# Threads per data dir for recovery
num.recovery.threads.per.data.dir=1

############################# Internal Topic Settings #############################

# Replication factors for internal topics (dev: 1 is fine)
offsets.topic.replication.factor=1
share.coordinator.state.topic.replication.factor=1
share.coordinator.state.topic.min.isr=1
transaction.state.log.replication.factor=1
transaction.state.log.min.isr=1

############################# Log Flush Policy #############################

# Messages flush intervals (optional; commented out)
#log.flush.interval.messages=10000
#log.flush.interval.ms=1000

############################# Log Retention Policy #############################

# Retention and segment sizes
log.retention.hours=168
#log.retention.bytes=1073741824
log.segment.bytes=1073741824
log.retention.check.interval.ms=300000
